/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void controlWindow_draw(PApplet appc, GWinData data) { //_CODE_:controlWindow:291229:
  appc.background(230);
} //_CODE_:controlWindow:291229:

public void pause_resume_click(GButton source, GEvent event) { //_CODE_:pause_resume:592749:
  paused = !paused;
  if (paused) {
    source.setText("Resume");
  } else {
    source.setText("Pause");
  }
} //_CODE_:pause_resume:592749:

public void speed_slider_change(GSlider source, GEvent event) { //_CODE_:speed_slider:501826:
  speed = source.getValueF();
} //_CODE_:speed_slider:501826:

public void obj_droplist_click(GDropList source, GEvent event) { //_CODE_:obj_droplist:570362:
  if (event == GEvent.SELECTED) {
    // Get the selected item
    int selected = source.getSelectedIndex();
    selectedObject = objects.get(selected);
  }
  showSelectedObjectValues();
  saveData();
} //_CODE_:obj_droplist:570362:

public void Omega0x_textfield_change(GTextField source, GEvent event) { //_CODE_:Omega0x_textfield:814141:
  saveData();
} //_CODE_:Omega0x_textfield:814141:

public void Omega0y_textfield_change(GTextField source, GEvent event) { //_CODE_:Omega0y_textfield:325439:
  saveData();
} //_CODE_:Omega0y_textfield:325439:

public void Omega0z_textfield_change(GTextField source, GEvent event) { //_CODE_:Omega0z_textfield:808334:
  saveData();
} //_CODE_:Omega0z_textfield:808334:

public void MOIx_textfield_change(GTextField source, GEvent event) { //_CODE_:MOIx_textfield:712048:
  saveData();
} //_CODE_:MOIx_textfield:712048:

public void MOIy_textfield_change(GTextField source, GEvent event) { //_CODE_:MOIy_textfield:433741:
  saveData();
} //_CODE_:MOIy_textfield:433741:

public void MOIz_textfield_change(GTextField source, GEvent event) { //_CODE_:MOIz_textfield:421961:
  saveData();
} //_CODE_:MOIz_textfield:421961:

public void setValues_click(GButton source, GEvent event) { //_CODE_:setValues:203165:
  setValues();
  saveData();
} //_CODE_:setValues:203165:

public void resetValues_click(GButton source, GEvent event) { //_CODE_:resetValues:758025:
  resetValues();
  saveData();
} //_CODE_:resetValues:758025:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Observer Frame");
  controlWindow = GWindow.getWindow(this, "Control Window", 0, 0, 600, 200, JAVA2D);
  controlWindow.noLoop();
  controlWindow.setActionOnClose(G4P.KEEP_OPEN);
  controlWindow.addDrawHandler(this, "controlWindow_draw");
  pause_resume = new GButton(controlWindow, 370, 130, 80, 40);
  pause_resume.setTextAlign(GAlign.CENTER, GAlign.BOTTOM);
  pause_resume.setText("Pause");
  pause_resume.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  pause_resume.addEventHandler(this, "pause_resume_click");
  speed_slider = new GSlider(controlWindow, 40, 110, 300, 80, 10.0);
  speed_slider.setShowValue(true);
  speed_slider.setShowLimits(true);
  speed_slider.setLimits(1.0, 0.0, 3.0);
  speed_slider.setNbrTicks(4);
  speed_slider.setShowTicks(true);
  speed_slider.setNumberFormat(G4P.DECIMAL, 2);
  speed_slider.setOpaque(false);
  speed_slider.addEventHandler(this, "speed_slider_change");
  obj_droplist = new GDropList(controlWindow, 210, 20, 130, 100, 3, 10);
  obj_droplist.setItems(loadStrings("object_list.txt"), 0);
  obj_droplist.addEventHandler(this, "obj_droplist_click");
  Omega0x_textfield = new GTextField(controlWindow, 60, 20, 120, 30, G4P.SCROLLBARS_NONE);
  Omega0x_textfield.setOpaque(true);
  Omega0x_textfield.addEventHandler(this, "Omega0x_textfield_change");
  Omega0y_textfield = new GTextField(controlWindow, 60, 50, 120, 30, G4P.SCROLLBARS_NONE);
  Omega0y_textfield.setOpaque(true);
  Omega0y_textfield.addEventHandler(this, "Omega0y_textfield_change");
  Omega0z_textfield = new GTextField(controlWindow, 60, 80, 120, 30, G4P.SCROLLBARS_NONE);
  Omega0z_textfield.setOpaque(true);
  Omega0z_textfield.addEventHandler(this, "Omega0z_textfield_change");
  MOIx_textfield = new GTextField(controlWindow, 390, 20, 120, 30, G4P.SCROLLBARS_NONE);
  MOIx_textfield.setOpaque(true);
  MOIx_textfield.addEventHandler(this, "MOIx_textfield_change");
  MOIy_textfield = new GTextField(controlWindow, 390, 50, 120, 30, G4P.SCROLLBARS_NONE);
  MOIy_textfield.setOpaque(true);
  MOIy_textfield.addEventHandler(this, "MOIy_textfield_change");
  MOIz_textfield = new GTextField(controlWindow, 390, 80, 120, 30, G4P.SCROLLBARS_NONE);
  MOIz_textfield.setOpaque(true);
  MOIz_textfield.addEventHandler(this, "MOIz_textfield_change");
  Omega0x_label = new GLabel(controlWindow, 20, 25, 40, 30);
  Omega0x_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Omega0x_label.setText("Ωx");
  Omega0x_label.setOpaque(false);
  Omega0y_label = new GLabel(controlWindow, 20, 55, 40, 30);
  Omega0y_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Omega0y_label.setText("Ωy");
  Omega0y_label.setOpaque(false);
  Omega0z_label = new GLabel(controlWindow, 20, 85, 40, 30);
  Omega0z_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Omega0z_label.setText("Ωz");
  Omega0z_label.setOpaque(false);
  Ix_label = new GLabel(controlWindow, 350, 25, 40, 30);
  Ix_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Ix_label.setText("Ix");
  Ix_label.setOpaque(false);
  Iy_label = new GLabel(controlWindow, 350, 55, 40, 30);
  Iy_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Iy_label.setText("Iy");
  Iy_label.setOpaque(false);
  Iz_label = new GLabel(controlWindow, 350, 85, 40, 30);
  Iz_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Iz_label.setText("Iz");
  Iz_label.setOpaque(false);
  setValues = new GButton(controlWindow, 525, 50, 60, 40);
  setValues.setTextAlign(GAlign.CENTER, GAlign.BOTTOM);
  setValues.setText("Run");
  setValues.addEventHandler(this, "setValues_click");
  resetValues = new GButton(controlWindow, 480, 130, 60, 40);
  resetValues.setTextAlign(GAlign.CENTER, GAlign.BOTTOM);
  resetValues.setText("Reset");
  resetValues.addEventHandler(this, "resetValues_click");
  controlWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controlWindow;
GButton pause_resume; 
GSlider speed_slider; 
GDropList obj_droplist; 
GTextField Omega0x_textfield; 
GTextField Omega0y_textfield; 
GTextField Omega0z_textfield; 
GTextField MOIx_textfield; 
GTextField MOIy_textfield; 
GTextField MOIz_textfield; 
GLabel Omega0x_label; 
GLabel Omega0y_label; 
GLabel Omega0z_label; 
GLabel Ix_label; 
GLabel Iy_label; 
GLabel Iz_label; 
GButton setValues; 
GButton resetValues; 
